### ISSUE TITLE
Place all example files in a folder named 1.0

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/TrainingDML-AI_SWG#1]
I suggest placing all example files in a folder named `1.0`.

This will make it easier to organise the examples in the future if there is a version 2.0 (which might not be backwards compatible).

`https://github.com/opengeospatial/TrainingDML-AI_SWG/tree/main/use-cases/examples/1.0/`

**Comment by ghobona** [comment]
Please also update Annex B to reflect the new path of the folders.

![Screenshot 2023-04-06 at 12 44 25](https://user-images.githubusercontent.com/18121038/230368767-c88b23dc-0cd7-4e79-8af5-0623b05edd54.png)

**Comment by RuixiangLiuWHU** [comment]
Thank you very much for your suggestions.
I have added the folder named `1.0` under `examples` and placed all of the example files into it.
I also changed the hyperlink in the standard document (.docx) to match the text narrative.
