### ISSUE TITLE
Problem when validating the WHU-RS19.json example file

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/TrainingDML-AI_SWG#11]
When I try to validate the file WHU-RS19.json, using the schema ai_eoTrainingDataset.json, I get a series of these error messages. Note that the same errors appear when using ai_trainingDataset.json to validate.

```
 $.data[line number].dataSources[0]: string found, object expected.
 $.data[line number].dataURL: string found, array expected.
```

When I checked the JSON file, I found this.

```
    {
      "type": "AI_EOTrainingData",
      "id": "airport_34",
      "dataSources": [
        "googleEarth"
      ],
      "dataURL": "image/Airport/airport_34.jpg",
      "labels": [
        {
          "type": "AI_SceneLabel",
          "class": "Airport"
        }
      ]
    }

```

Looking at Figure 7 of the TrainingDML-AI Part 1, the validator and the JSON Schema are correct. I think the issue is with the example file.

https://docs.ogc.org/is/23-008r3/23-008r3.html#figure-uml-trainingdata

**Comment by ghobona** [comment]
In the end, I had to make these edits to a local copy of the file in order to get it to validate.

https://github.com/opengeospatial/ets-trainingdmlai10-part2/commit/8afc7c2423cbcf9bafe3c8a3c154a5462b1c453b

The extracts from whu_rs19 that are in the [Standards document](https://portal.ogc.org/files/?artifact_id=108268&version=1) are correct per the schema. So I think the correct **WHU-RS19.json** file exists but had not been pushed to the GitHub repo.

@geopyue Could you please ask the team to check if they might have the file on their local machines?

**Comment by Relifest** [comment]
> @geopyue Could you please ask the team to check if they might have the file on their local machines?

To address the issue you mentioned, we have made modifications to the examples. Those examples follow the standards of the previous version. We will upload examples that follow the latest standards as soon as possible. We deeply apologize for any inconvenience caused to you.

**Comment by RuixiangLiuWHU** [comment]
Hi, @ghobona Our team has updated all of the json and xml encoding examples to keep them consistent with the schemas. We have validate them one by one through schemas. If you have any further concerns, please let us know, we will address the issues as soon as possible.

**Comment by ghobona** [comment]
Thanks @RuixiangLiuWHU . I can confirm that the updated version of WHU-RS19.json passed the validation test.
