### ISSUE TITLE
Example AI_EOTrainingDataset file containing DataQuality object is needed

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/TrainingDML-AI_SWG#15]
None of the example files contain an AI_EOTrainingDataset that has a ‘DataQuality’ object.

The only file with a ‘DataQuality’ JSON object that I could find is WHU-RS19-quality.json. However, the root element of the JSON Object is  the ‘DataQuality’ object. 

Given that the AI_TrainingDataset conformance class is mandatory, it means that the WHU-RS19-quality.json does not comply with the AI_TrainingDataset  conformance class.

Could you please provide create an example based on WHU-RS19.json but with a quality element that contains a DataQuality object?

**Comment by RuixiangLiuWHU** [comment]
Hi @ghobona, Thanks for the comment. Our team has updated the [WHU-RS19-quality.json](https://github.com/opengeospatial/TrainingDML-AI_SWG/blob/main/use-cases/examples/1.0/WHU-RS19-quality.json) to the full dataset level. It now complies to the AI_EOTrainingDataset schema, containing the DataQuality object.

**Comment by ghobona** [comment]
Hi @RuixiangLiuWHU @geopyue @YongyiMi, that's excellent! Thank you.

I can confirm that the updated version of WHU-RS19-quality.json passes the validation test.
