### ISSUE TITLE
Example files for changesets needed

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/TrainingDML-AI_SWG#19]
One of the properties of AI_TrainingDataset is 'changesets'.

There are currently no example files of an AI_TrainingDataset/AI_EOTrainingDataset containing a 'changesets' element.

Please create an example AI_TrainingDataset/AI_EOTrainingDataset  file that contains a 'changesets' element.

**Comment by RuixiangLiuWHU** [comment]
@ghobona Thank you for the support. One member of our team will soon create the expected example and reply here.

**Comment by YongyiMi** [comment]
Hi @ghobona , Thanks for the comment. Our team has updated the DOTA-v1.5-changeset.json and DOTA-v1.5-changeset.xml to the full dataset level. They now complie to the AI_EOTrainingDataset schema, containing the AI_TDChangeset type.

**Comment by ghobona** [comment]
Hi @YongyiMi , thank you for updating the file.
