### ISSUE TITLE
Part 2: URI references to schema folder are missing part2 segment

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/TrainingDML-AI_SWG#20]
The Part 2 document has multiple references to http://schemas.opengis.net/trainingdml-ai/1.0/

Please change from http://schemas.opengis.net/trainingdml-ai/1.0/ to http://schemas.opengis.net/trainingdml-ai/part2/1.0/

**Comment by RuixiangLiuWHU** [comment]
@ghobona, thank you for the comment. I have changed the links of schemas in ats. Another concern I have is that when should we upload the schemas into [http://schemas.opengis.net/trainingdml-ai/part2/1.0/](http://schemas.opengis.net/trainingdml-ai/part2/1.0/), and how?

**Comment by ghobona** [comment]
@RuixiangLiuWHU OGC staff upload the schemas to http://schemas.opengis.net/ during the release process. This will happen after the Technical Committee and Executive Planning Committee votes have completed.

**Comment by ghobona** [comment]
@RuixiangLiuWHU Thanks for changing the links.
