### ISSUE TITLE
1.0/WHU-building.json issue

### ISSUE THREAD

**Issue by photonbit** [opengeospatial/TrainingDML-AI_SWG#22]
Hello!

I am working in the issue of the validation using pytdml, which is almost done, but I've found the following issues in the following example, that is the one used in the library.

https://github.com/opengeospatial/TrainingDML-AI_SWG/blob/main/use-cases/examples/1.0/WHU-building.json

The file in pytdml was older, so I am using the one in this repo, I just made a copy from that link. I believe that this file has some issues in the `AI_EOTrainingData` inside the `AI_EOTrainingDataset`:

- AI_EOTrainingData should contain a `extent` instead of a `bbox` 

I found some more issues handling this file, but the rest belong to pytdml instead, I will open a pull request there pointing to this issue.

**Comment by RuixiangLiuWHU** [comment]
@photonbit  Thank you for the comment. I have fixed the error in the WHU-building JSON example.
