### ISSUE TITLE
Possible error in dateTime definition

### ISSUE THREAD

**Issue by photonbit** [opengeospatial/TrainingDML-AI_SWG#29]
Hello!

In a recent pull request of pytdml, 张扬 created a new test that I believe it is raising an error in the definition of `dateTime`. The current 1.0 and 1.1 definition read as follows:

```
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/opengeospatial/TrainingDML-AI_SWG/main/schemas/1.0/json_schema/dateTime.json",
    "title": "DateTime",
    "oneOf": [
        {
            "type": "string",
            "format": "date-time"
        },
        {
            "type": "string",
            "format": "date"
        },
        {
            "type": "string",
            "format": "time"
        },
        {
            "type": "string",
            "pattern": "^(19|20)\\d{2}$"
        },
        {
            "type": "string",
            "pattern": "^(19|20)\\d{2}-(0[1-9]|1[0-2])$"
        }
    ]
}
``` 

The example value, `2023-10-27T14:30:00`, proposed by @Relifest in the test validates against 4 of the 5 possible definitions in the standard. According to https://json-schema.org/understanding-json-schema/reference/combining#anyOf `anyOf` should be used instead.

**Comment by Relifest** [comment]
We have made corresponding modifications to solve this problem. At present, the test value, `2023-10-27T14:30:00`, can pass the test correctly.

**Comment by Relifest** [comment]
We have made corresponding modifications to solve this issue. At present, the test value, `2023-10-27T14:30:00`, can pass the test correctly. Thank you for raising this issue.

**Comment by photonbit** [comment]
Solved by https://github.com/opengeospatial/TrainingDML-AI_SWG/pull/30
